import { Geist, Geist_Mono } from "next/font/google";
import { Roboto } from "next/font/google";
import Header from "./global_components/Header";
import "./globals.css";
import { AuthProvider } from "./context.js/AuthContext";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"], // customize as needed
  variable: "--font-roboto",
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Telecure",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable}  antialiased `}>
        <AuthProvider>
          <Header />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
